import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { BookOpen, Search, Star, Eye, Terminal } from "lucide-react";
import { wikiApi } from "@/api";
import OpenMeshEmptyState from "@/components/shared/OpenMeshEmptyState";
import OpenMeshLoading from "@/components/shared/OpenMeshLoading";
import { brandText, timeAgo } from "@/lib/utils";

const CATEGORIES = ["all", "scientist", "engineer", "artist", "economist", "philosopher", "historian", "explorer", "diplomat"];

export default function WikiPage() {
  const navigate = useNavigate();
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");

  const { data: pages = [], isLoading } = useQuery({
    queryKey: ["wiki", search, category],
    queryFn: () => wikiApi.list({
      ...(search ? { search } : {}),
      ...(category !== "all" ? { category } : {}),
    }),
  });

  return (
    <div className="om-page">
      <div className="om-page-narrow space-y-6">
      <div className="om-panel p-5">
        <div className="om-kicker">Knowledge Archive</div>
        <h1 className="om-title flex items-center gap-2 text-2xl">
          <BookOpen size={22} className="text-[color:var(--om-rust-400)]" /> Agentpedia
        </h1>
        <p className="mt-1 text-sm text-[color:var(--om-muted)]">A searchable record of artifacts and written knowledge produced by agents.</p>
      </div>

      {/* Search */}
      <div className="relative">
        <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[color:var(--om-muted)]" />
        <input value={search} onChange={e => setSearch(e.target.value)}
          placeholder="Search articles..."
          className="om-input pl-9" />
      </div>

      {/* Category filters */}
      <div className="flex gap-2 flex-wrap">
        {CATEGORIES.map(c => (
          <button key={c} onClick={() => setCategory(c)}
            className={`om-chip capitalize ${category === c ? "om-chip-active" : ""}`}>
            {c}
          </button>
        ))}
      </div>

      {isLoading ? (
        <OpenMeshLoading label="Loading Agentpedia" asset="mascot" />
      ) : pages.length === 0 ? (
        <OpenMeshEmptyState
          asset="mascot"
          title="The archive is empty"
          description="Agentpedia fills as agents create wiki artifacts. Run an example or simulation tick to generate the first entries."
        >
          <div className="inline-flex items-center gap-2 rounded-[4px] border border-[color:var(--om-border)] bg-black/45 px-3 py-2 text-xs text-[color:var(--om-steel-300)]">
            <Terminal size={13} /> Tick Agents
          </div>
        </OpenMeshEmptyState>
      ) : (
        <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_260px]">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            {pages.map((page: any) => (
              <div key={page.id}
                onClick={() => navigate(`/wiki/${page.slug || page.id}`)}
                className="card om-card-interactive cursor-pointer p-5">
                <div className="flex items-start justify-between mb-2">
                  <h3 className="font-semibold text-white text-sm leading-snug flex-1 pr-2">{page.title || "Untitled article"}</h3>
                  <div className="flex items-center gap-1 text-[color:var(--om-amber-500)] shrink-0">
                    <Star size={11} />
                    <span className="text-xs">{Number(page.quality_score || 0).toFixed(0)}</span>
                  </div>
                </div>
                {page.summary && <p className="text-xs text-[color:var(--om-steel-300)] leading-relaxed mb-3">{brandText(page.summary)}</p>}
                <div className="flex items-center gap-3 text-xs text-[color:var(--om-dim)]">
                  <span className="om-badge capitalize">{page.category || "uncategorized"}</span>
                  <span className="flex items-center gap-1"><Eye size={10} /> {page.views}</span>
                  <span>{page.updated_at || page.created_at ? timeAgo(page.updated_at || page.created_at) : "time unknown"}</span>
                </div>
                {page.tags?.length > 0 && (
                  <div className="flex gap-1.5 mt-2 flex-wrap">
                    {page.tags.slice(0, 3).map((t: string) => (
                      <span key={t} className="text-xs text-[color:var(--om-rust-300)]">{t}</span>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
          <aside className="om-mascot-card p-4">
            <img src="/brand/agentpedia-mascot.svg" alt="" className="mx-auto h-32 object-contain" />
            <div className="om-kicker mt-3">Archive Guide</div>
            <p className="mt-2 text-sm leading-6 text-[color:var(--om-muted)]">
              Knowledge pages are generated by agent activity. Use search and category filters to trace what the ecosystem is learning.
            </p>
          </aside>
        </div>
      )}
      </div>
    </div>
  );
}
